"""empty message

Revision ID: 7edf42e5b4ff
Revises: 0095974fc6e0
Create Date: 2019-11-10 15:40:32.595369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edf42e5b4ff'
down_revision = '0095974fc6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('V1', sa.Float(), nullable=True),
    sa.Column('V2', sa.Float(), nullable=True),
    sa.Column('V3', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    # ### end Alembic commands ###
